### ISSUE TITLE
Can't install using "npm install mail-listener" on Windows 7.

### ISSUE THREAD

**Issue by andy-g** [circuithub/mail-listener#1]
I tried to install mail-listener, but it fails and throws the following error ('node-waf' is not recognized as an internal or external command, operable program or batch file.).

Below is the NPM output.

Thanks

> npm install mail-listener
> npm http GET https://registry.npmjs.org/mail-listener
> npm http 200 https://registry.npmjs.org/mail-listener
> npm http GET https://registry.npmjs.org/mail-listener/-/mail-listener-0.0.3.tgz
> npm http 200 https://registry.npmjs.org/mail-listener/-/mail-listener-0.0.3.tgz
> npm http GET https://registry.npmjs.org/imap
> npm http GET https://registry.npmjs.org/mailparser
> npm http GET https://registry.npmjs.org/coffee-script
> npm http 200 https://registry.npmjs.org/coffee-script
> npm http GET https://registry.npmjs.org/coffee-script/-/coffee-script-1.3.1.tgz
> npm http 200 https://registry.npmjs.org/coffee-script/-/coffee-script-1.3.1.tgz
> npm http 200 https://registry.npmjs.org/imap
> npm http GET https://registry.npmjs.org/imap/-/imap-0.3.0.tgz
> npm http 200 https://registry.npmjs.org/mailparser
> npm http GET https://registry.npmjs.org/mailparser/-/mailparser-0.2.24.tgz
> npm http 200 https://registry.npmjs.org/imap/-/imap-0.3.0.tgz
> npm http 200 https://registry.npmjs.org/mailparser/-/mailparser-0.2.24.tgz
> npm http GET https://registry.npmjs.org/iconv
> npm http GET https://registry.npmjs.org/mimelib
> npm http 200 https://registry.npmjs.org/iconv
> npm http GET https://registry.npmjs.org/iconv/-/iconv-1.1.3.tgz
> npm http 200 https://registry.npmjs.org/mimelib
> npm http GET https://registry.npmjs.org/mimelib/-/mimelib-0.1.15.tgz
> npm http 200 https://registry.npmjs.org/iconv/-/iconv-1.1.3.tgz
> npm http 200 https://registry.npmjs.org/mimelib/-/mimelib-0.1.15.tgz
> 
> iconv@1.1.3 preinstall \nodejs\node_modules\mail-listener\node_modules\mailparser\node_modules\iconv
> node-waf configure

'node-waf' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! iconv@1.1.3 preinstall: `node-waf configure`
npm ERR! `cmd "/c" "node-waf configure"` failed with 1
npm ERR!
npm ERR! Failed at the iconv@1.1.3 preinstall script.
npm ERR! This is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure
npm ERR! You can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.
npm ERR!
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "mail-listener"
npm ERR! cwd \nodejs
npm ERR! node -v v0.6.15
npm ERR! npm -v 1.1.16
npm ERR! code ELIFECYCLE
npm ERR! message iconv@1.1.3 preinstall: `node-waf configure`
npm ERR! message `cmd "/c" "node-waf configure"` failed with 1
npm ERR! errno {}
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     \nodejs\npm-debug.log

**Comment by podviaznikov** [comment]
After updating https://github.com/andris9/mailparser should work on Windows
