### ISSUE TITLE
listerner for multiple emails.

### ISSUE THREAD

**Issue by chirag04** [circuithub/mail-listener#15]
Looking for a example to listen for multiple emails. Any heads up?

I need to listen for multiple emails which are going to be configured dynamically and not when the script boots up.

**Comment by anotheri** [comment]
@chirag04 It's complex goal. But maybe [this answer](https://github.com/circuithub/mail-listener/issues/14#issuecomment-19026302) can help you.

You can change **lstnr.js** file (from example) for getting information about all your emails from db and creating listener for each of them and than restart this script as a child process from a handler (file **main.js**). In turn, handler should listen changes in your email collection in db. Or something like this.

**Comment by chirag04** [comment]
Yes, I'm doing the same. Using forever to keep the script running. Added tcp server which will accept multiple emails to be added dynamically and that will create multiple listener .
