### ISSUE TITLE
imap 0.8 changes

### ISSUE THREAD

**Issue by mscdex** [circuithub/mail-listener#25]
I saw your dependency on imap will automatically include the new minor version (0.8). Just to give you a heads up, there were some API changes which are documented [here](https://github.com/mscdex/node-imap/wiki/API-changes-between-v0.7-and-v0.8).

**Comment by chirag04** [comment]
@podviaznikov

It would be awesome to have the updated version to node-imap with mail-listener. We will use mail-listener in production soon.

**Comment by ghost** [comment]
I'd love to see mail-listener updated to work with node-imap 0.8.0 too.

**Comment by Rajan** [comment]
Same here. Looking forward to use with 0.8 node-imap.
