### ISSUE TITLE
mail listener breaks on receiving new mails

### ISSUE THREAD

**Issue by chirag04** [circuithub/mail-listener#7]
I have node version 0.10.2 on Mac.

I applied the patch below to imap library for connecting to gmail.
https://github.com/mscdex/node-imap/issues/181

But when i receive a new mail, Mail-listener breaks down. Below is the stack trace.

3 Apr 13:47:06 - new mail arrived with id 1

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error
    at CleartextStream.write [as _write](tls.js:332:31)
    at doWrite (_stream_writable.js:211:10)
    at writeOrBuffer (_stream_writable.js:201:5)
    at CleartextStream.Writable.write (_stream_writable.js:172:11)
    at ImapConnection._send (/Users/Novanet/Desktop/node-mailer/node_modules/mail-listener/node_modules/imap/lib/imap.js:1546:22)
    at ImapConnection._send (/Users/Novanet/Desktop/node-mailer/node_modules/mail-listener/node_modules/imap/lib/imap.js:1537:19)
    at ImapConnection._search (/Users/Novanet/Desktop/node-mailer/node_modules/mail-listener/node_modules/imap/lib/imap.js:891:8)
    at ImapConnection.search (/Users/Novanet/Desktop/node-mailer/node_modules/mail-listener/node_modules/imap/lib/imap.js:883:8)
    at ImapConnection.<anonymous> (/Users/Novanet/Desktop/node-mailer/node_modules/mail-listener/dist/mail.listener.js:52:35)
    at ImapConnection.EventEmitter.emit (events.js:95:17)

**Comment by BlakeLucchesi** [comment]
I can confirm I'm getting the same error when a new email arrives.  I'm connecting to a gmail account.  Also to note, I applied the patch suggested here https://github.com/mscdex/node-imap/commit/0b042e0e14dfde6a26e881bbbcf0c6f9746da51e and that at least got me to the point where I could connect to the gmail account and begin listening for emails.  Will post more if I'm able to track down the reason for this specific issue (error on incoming email).

**Comment by BlakeLucchesi** [comment]
I believe this is a connection issue as a result of the latest version of node.  I just downgraded to node 0.8.1 and it's reading the emails as expected.

Here is what I was able to find with node: 0.10.1 and the following npm package versions:

```
├─┬ mail-listener@0.4.0 
│ ├─┬ imap@0.7.8 
│ │ └── utf7@1.0.0 
│ └─┬ mailparser@0.3.4 
│   ├─┬ encoding@0.1.6 
│   │ └── iconv-lite@0.2.7 
│   ├── iconv@2.0.4 
│   ├── mime@1.2.9 
│   └─┬ mimelib@0.2.12 
│     └── addressparser@0.1.3
```

I added a debug statement to imap.js (part of the node-imap package) to line 1547, right above where it is referenced in your stack trace above inside the ImapConnection._send method.

```
console.log(this._state.conn) 
```

At the bottom of the output I noticed the following:

```
authorizationError: 'Hostname/IP doesn\'t match certificate\'s altnames' }
```

which leads me to believe there is an issue in the gmail ssl certificate validation that is happening during the connection.  I'm still really new to node so I don't know how else to debug this further, but this is what I was able to find.

**Comment by podviaznikov** [comment]
@chirag04, @BlakeLucchesi thank you for reporting this problem and posting all details.
I will investigate this bug today.

**Comment by anotheri** [comment]
@chirag04 I had this bug too:

```
events.js:72
throw er; // Unhandled 'error' event
^
Error
at CleartextStream.write as _write
at doWrite (_stream_writable.js:211:10)
at writeOrBuffer (_stream_writable.js:201:5)
at CleartextStream.Writable.write (_stream_writable.js:172:11)
...
```

This error occurred yesterday with patched `node-imap` and at the last unstable version of `node v0.11.0` on `Ubuntu 12.10`. But it works fine with `node v0.10.4`. So you can try to use this version `v0.10.4`.
Or I'll try to chek it on the OS X in the nearest days.

**Comment by chirag04** [comment]
@anotheri  Thanks for the info. I'm onto v0.11.1-pre. Will revert back to 10.4

**Comment by podviaznikov** [comment]
For now I would probably recommend to use node 0.8.\* for this library. 

As you mentioned this problem is gone with node 0.10.4 but I noticed another problem in imap library.

So I'm getting following error with node 0.10.4 and newest versions of dependencies:

```
/Users/podviaznikov/circuithub/mail-listener/node_modules/imap/lib/imap.js:340
              for (var i=0, len=labels.length; i<len; ++i)
                                      ^
TypeError: Cannot read property 'length' of undefined
  at CleartextStream.ondata (/Users/podviaznikov/circuithub/mail-listener/node_modules/imap/lib/imap.js:340:39)
```

I will check if imap has that issue posted.

**Comment by chirag04** [comment]
I think this is working fine now with node v10.4+
